name: NDManager unit tests

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

env:
    NDMANAGER_ENDF6: ${HOME}/.ndmanager/endf6
    NDMANAGER_HDF5: ${HOME}/.ndmanager/hdf5
    NJOY: ${HOME}/NJOY2016/build/njoy

jobs:
    build:
        runs-on: ubuntu-24.04
        strategy:
            matrix:
                python-version: ["3.11", "3.12", "3.13"]
        name: "Python ${{ matrix.python-version }}"
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with: 
                python-version: ${{ matrix.python-version }}

            - name: Installing NJOY
              shell: bash
              run: |
                  echo "$HOME/NJOY2016/build" >> $GITHUB_PATH
                  $GITHUB_WORKSPACE/tools/ci/install_njoy.sh
             
            - name: Installing OpenMC
              shell: bash
              run: |
                  $GITHUB_WORKSPACE/tools/ci/install_openmc.sh

            - name: Installing NDManager
              shell: bash
              run: |
                pip install --group dev .

            - name: Pytest
              shell: bash
              run: |
                python -m coverage run --source=ndmanager -m pytest tests/ 

            - name: Coveralls GitHub Action
              uses: coverallsapp/github-action@v2.3.4

                