name: NDManager unit tests

on:
    push:
        branches: [main, test]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-24.04
        strategy:
            matrix:
                python-version: ["3.12"]
        name: "Python ${{ matrix.python-version }}"
        steps:
            - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

